# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

en-main:
    - label: Studio
      path: en/studio
    - label: Commercial
      path: en/commercial
    - label: Film
      path: en/film
    - label: Audiobooks
      path: en/audiobooks
    - label: Artist
      path: en/artist
    - label: Awards
      path: en/awards
      class: beside
    - label: Contact
      path: en/contact

de-main:
    - label: Studio
      path: de/studio
    - label: Werbung
      path: de/werbung
    - label: Film
      path: de/film
    - label: Hoerspiele
      path: de/hoerspiele
    - label: Künstler
      path: de/kuenstler
    - label: Awards
      path: de/awards
      class: beside
    - label: Kontakt
      path: de/kontakt
