# Optional config file for the theme.

# Variables that are in this file, can be used in your twig template like {{ theme.foo }}
# Note: If variables do not immediately show up, clear the cache, in the Bolt Backend.

foo: bar


# Template filenames. If you 're creating a theme for distribution, you can specify
# the filenames of the templates here. The templates you will set in this config
# file will override the ones in the global app/config/config.yml, so beware!
# maintenance_template: maintenance_default.twig
# homepage_template: index.twig
# record_template: record.twig
# listing_template: listing.twig
# search_results_template: listing.twig

templatefields:
    kontakt.twig:
        team:
            type: html
            label: Team
        impressum:
            type: html
            label: Impressum

# There can be defined the templates for the template chooser
#templateselect:
#    templates:
#        record:
#            name: 'Template for Records'
#            filename: 'record.twig'
